# Generated by Django 6.0.4 on 2026-05-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('attendance_percentage', models.FloatField(help_text='Attendance percentage (0-100)')),
                ('previous_grade', models.FloatField(help_text='Previous year grade (0-100)')),
                ('study_time', models.FloatField(help_text='Average study hours per week')),
                ('failures_past', models.IntegerField(help_text='Number of past failures')),
                ('family_support', models.IntegerField(help_text='Family support level (1-10)')),
                ('extracurricular_activities', models.BooleanField(default=False)),
                ('internet_access_at_home', models.BooleanField(default=True)),
                ('parent_education_level', models.IntegerField(default=5, help_text='Parent education (1-10)')),
                ('current_grade', models.CharField(blank=True, choices=[('A', 'A (Excellent)'), ('B', 'B (Good)'), ('C', 'C (Average)'), ('D', 'D (Below Average)'), ('F', 'F (Fail)')], max_length=1, null=True)),
                ('final_score', models.FloatField(blank=True, help_text='Final exam score (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
